# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

#version
version: "1.0"


title: First Jekyll Project
email: gonglong.gatech@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  First play with Jekyll.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:8089" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: lgong30
github_username:  lgong30

# Build settings
sass:
  sass_dir: _sass
  style: compressed
include: ['_pages']
# markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge


# 分页设置
paginate: 10
paginate_path: "blog/page:num/"




# Customized variables
research_interests:
  - data streaming
  - online social networking
  - lightweight scheduling algorithms for crossbar switches, and data center networks

advisor:
  MS:
    name: Zuqing Zhu
    url: http://www.zuqingzhu.info/
  PhD:
    name: Jun (Jim) Xu
    url: http://www.cc.gatech.edu/~jx/

author:
  full_name: Long Gong
  email: gonglong.gatech@gmail.com
  url: http://cc.gatech.edu/~lgong30

education:
  - edu1:
    institution: University of Science and Technology of China (USTC)
    address: Hefei, Anhui, China
    degree: B.E.
    major: Electronic Enginerring
    started: 2008
    duration: (2005 - 2012)
    description: ""
  - edu2:
    institution: University of Science and Technology of China (USTC)
    address: Hefei, Anhui, China
    degree: M.E.
    major: Electronic Enginerring
    started: 2012
    duration: (2012 - 2015)
    description: ""
  - edu3:
    institution: Georgia Institution of Technology
    address: Atlanta, GA, USA 
    degree: PhD
    major: Computer Science
    started: 2015
    duration: (2015 - Present)
    description: ""

# Gems
gems: [jekyll-paginate]